### ISSUE TITLE
Converting nested JSONObject instances is slow

### ISSUE THREAD

**Issue by darinwilson** [darinwilson/moran#4]
Per [this post](http://community.rubymotion.com/t/moran-a-json-parser-generator-for-android/365/7) from @nickyhajal:

> Unfortunately today I'm finding that for some requests the conversion of nested JSONObjects -> Ruby hash can take a long time... Up to 30 seconds.
>
> I'm thinking maybe I'll just have to suck it up and use the JSONObject API, though I wonder if there could be a baked in translation of JSONObject at some point in RM.

**Comment by darinwilson** [comment]
How many levels of nesting are we talking about where you see this slowness?

**Comment by nickyhajal** [comment]
Here's an example JSON response causing issues: http://pastebin.com/raw.php?i=eb7eBw4g

I'm not sure if it's the nesting or the sheer size of the response, though it doesn't seem *that* big.

**Comment by darinwilson** [comment]
Just so I'm clear: is this something that's coming to you as a JSON string, or as a JSONObject? I just want to make sure I'm looking at the right part of the code :)

**Comment by nickyhajal** [comment]
I am using `Volley::Toolbox::JSONObjectRequest` so it is coming in as a `JSONObject` and I'm using `Hash.from_json_object` to convert it.

I did try using `StringRequest` and than `Moran.parse` to turn that into a Ruby hash but seemed to experience the same slow processing in the conversion.

**Comment by darinwilson** [comment]
@nickyhajal Commit 01a49e2c4a8ab182847a62db5103818330c58b1c should fix this issue - I was able to remove some extra type conversion when parsing, and your test JSON is getting parsed quite quickly. 

I pushed a new gem version for this change, so please give it a try and see if it's working better. I'm closing this issue for now, but will reopen it if you're still having problems.
