### ISSUE TITLE
Parsing with array as root element

### ISSUE THREAD

**Issue by ulrik** [darinwilson/moran#5]
Moran.parse("[1,2,3]")

Results in: 

Java exception raised: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.rubymotion.Hash out of START_ARRAY token

**Comment by darinwilson** [comment]
Whoops! Forgot about that case 😦

This should be fixed in master as of d00ca97 - can you give it a try? If it works, I'll push a new version.

**Comment by darinwilson** [comment]
Per [this comment](https://github.com/darinwilson/moran/commit/d00ca974143cb2d7fe2aab1dae9af0e932e14282#commitcomment-12320706) from @ulrik, this fix is working. This version is now in rubygems as 0.6. Thanks @ulrik! :)
